api_ticket = {
    "tenant_feed_name": "midamerican_tickets",
    "dig_ticket": {
        "ticket_id": "GK-TEST",
        "call_center": "Test",
        "service_territory": "MidAmerican",
        "ticket_type": "TEST",
        "daily_sequence_number": 1,
        "reported_datetime": "2024-02-02 13:34:54.066",
        "work_start_datetime": "2024-02-03 13:34:54.066",
        "legal_due_datetime": "2024-02-04 13:34:54.066",
        "address": "924 26TH AVE & S 10TH ST COUNCIL BLUFFS, IA",
        "street_number": "924",
        "street_name": "26TH AVE",
        "city": "COUNCIL BLUFFS",
        "state": "IA",
        "county": "POTTAWATTAMIE",
        "cross_street_1": "S 10TH ST",
        "excavator_name": "ARYMOND PLUMBING",
        "excavator_type": None,
        "excavator_phone_number": "(712)314-9738",
        "excavator_address": "2127 S 8TH ST",
        "excavator_city": "COUNCIL BLUFFS",
        "excavator_state": "IA",
        "excavator_postal_code": "51501",
        "caller_name": "Tester Caller",
        "site_contact_name": "Test Contact Name",
        "work_done_for": "HOMEOWNER",
        "work_type": "EMERGENCY - REPAIR GAS LEAK",
        "has_boring": True,
        "has_white_paint": False,
        "work_description": "LOCATE AND MARK ALL UTILITIES ON THE PROPERTY OF 1428 N SUMMIT. INCLUDE ALL EASEMENTS AND RIGHT OF WAYS.",
        "ticket_url": "https://ia.itic.occinc.com/H7E4-224-RK2-LAX",
        "station_code": "TEST",
    },
    "dig_ticket_raw": {
        "text": '{"ticket_id":"TEST-1","call_center":"Test","service_territory":"Iowa","ticket_type":"TEST","daily_sequence_number":1,"reported_datetime":"2024-02-02 13:34:54.066","work_start_datetime":"2024-02-03 13:34:54.066","legal_due_datetime":"2024-02-04 13:34:54.066","address":"924 26TH AVE & S 10TH ST COUNCIL BLUFFS, IA","street_number":"924","street_name":"26TH AVE","city":"COUNCIL BLUFFS","state":"IA","county":"POTTAWATTAMIE","cross_street_1":"S 10TH ST","excavator_name":"ARYMOND PLUMBING","excavator_type":null,"excavator_phone_number":"(712)314-9738","excavator_address":"2127 S 8TH ST","excavator_city":"COUNCIL BLUFFS","excavator_state":"IA","excavator_postal_code":"51501","caller_name":"Tester Caller","site_contact_name":"Test Contact Name","work_done_for":"HOMEOWNER","work_type":"EMERGENCY - REPAIR GAS LEAK","has_boring":true,"has_white_paint":false,"work_description":"LOCATE AND MARK ALL UTILITIES ON THE PROPERTY OF 1428 N SUMMIT. INCLUDE ALL EASEMENTS AND RIGHT OF WAYS.","ticket_url":"https://ia.itic.occinc.com/H7E4-224-RK2-LAX","station_code":"TEST"}',
        "encoding": "json",
    },
}
